apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: TODO:
  namespace: le-pro
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: TODO:
    spec:
      containers:
      - name: TODO:
        image: ccr.ccs.tencentyun.com/le_pro/TODO::IMAGE_VERSION
        ports:
        - name: default
          containerPort: 7001
        env:
        - name : EGG_SERVER_ENV
          value : 'prod'
      imagePullSecrets:
      - name: qcloudregistrykey
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: TODO:
  name: TODO:
  namespace: le-pro
spec:
  ports:
  - port: 80
    targetPort: 7001
    name: default
  selector:
    app: TODO: